### PR TITLE
Enable multiple plugin instances

### LINKED ISSUE #33: The Selector does not actually select...
This is not a problem with only 1 menu but if you want to use multiples it becomes a problem...

For example if you make both a left and right side menu. the last instance overrides all previous ones...

This seems to be due to the design of the plugin frame work. This post better explains what I mean:
https://stackoverflow.com/a/22976877/1815624

This other post has helped me:
https://stackoverflow.com/a/24359224/1815624

### PR DESCRIPTION
**Pull request by CrandellWS**
Fixes #33

http://jsfiddle.net/nUzJN/286/

screenshot from 2018-11-06 15-47-02

This is primarily the same as it was...just a little more versatile...

### CODE REVIEW

**Comment by CrandellWS** [comment]
The return value allows you to chain jQuery events like this:

```
$('#testleft').data('bootSideMenu').open().css('margin-left', 300)
```

**Comment by CrandellWS** [comment]
@AndreaLombardo please feel free to revamp this as desired... hope it helps you create a better version 

fyi: One might want make sure the menu exists before calling methods on it.

```
var leftMenu = $('#testleft').data('bootSideMenu');
if(leftMenu != null){
	leftMenu.open();
}
```

**Comment by CrandellWS** [comment]
So I had to use a timeout function to auto close the menu upfront. perhaps there is a better way to handle that idk but it works for me.

```
    $(document).ready(function () {
        $('#testleft').BootSideMenu({
            side: "left",
            closeOnClick: false,
            pushBody: false,
            width:'default'
        });
        $('#testright').BootSideMenu({
            side: "right",
            closeOnClick: false,
            pushBody: false,
            onTogglerClick: function () {
                //alert("You clicked the arrow!");
            },
            width:'default'
        });
        setMenuVars();        
    });
    
        var leftMenu, rightMenu;
        function setMenuVars(){
            leftMenu = $('#testleft').data('BootSideMenu');
            setTimeout(function(){
                console.log('is closing');
                closeLeftMenu();
            }, 1);
            
            rightMenu = $('#testright').data('BootSideMenu');
            setTimeout(function(){
                closeRightMenu();
            }, 1);
        }
    
        function closeLeftMenu(){
            if(leftMenu != null){
	            leftMenu.close();
            } 
        }
        
        function closeRightMenu(){
            if(rightMenu != null){
	            rightMenu.close();
            }
        }
```

**Comment by AndreaLombardo** [comment]
Thanks @CrandellWS and sorry for the long absence.
Sure your code will work because I have no time to check and test.

Thanks again

**Pull request merged**
